# Usage example:
# oc new-app -f ./ingress-gateway.yaml \
#   -p INGRESS_GATEWAY_NAME=microservices-demo-ingressgateway
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ingress-gateway
message: Gateway and routing rules have been created.
metadata:
  annotations:
    description: Gateway and routing rules
  name: ingress-gateway
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: ${INGRESS_GATEWAY_NAME}
  spec:
    selector:
      istio: ${INGRESS_GATEWAY_NAME}
    servers:
    - hosts:
      - '*'
      port:
        number: 80
        name: http
        protocol: HTTP
    - hosts:
      - '*'
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE # enables HTTPS on this port
        serverCertificate: /etc/certs/cert-chain.pem
        privateKey: /etc/certs/key.pem
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: app-ui-gateway
  spec:
    hosts:
    - '*'
    gateways:
    - ${INGRESS_GATEWAY_NAME}
    http:
    - route:
      - destination:
          host: app-ui
          port:
            number: 8080
parameters:
- description: The name for the ingress gateway.
  displayName: Ingress Gateway Name
  name: INGRESS_GATEWAY_NAME
  required: true
  value: microservices-demo-ingressgateway